### ISSUE TITLE
Unable to precompile from GitHub due to `isgibbscomponent not defined`

### ISSUE THREAD

**Issue by kowale** [phipsgabler/AutoGibbs.jl#3]
Hello! Installing master of AutoGibbs by `] add https://github.com/phipsgabler/AutoGibbs.jl` and trying to precompile it by `using AutoGibbs` results in `UndefVarError: isgibbscomponent not defined` on Julia 1.5.0 with Turing 0.13.0.

The stack trace suggests that while trying to include `src/auto_conditional.jl` the line
```
Turing.isgibbscomponent(::AutoConditional) = true
```
fails with the error above. Similar line is in `src/static_conditional.jl` as well. I also tried running `using Turing` first and then trying to precompile AutoGibbs, but to no avail.

When pasting the include statements from `src/AutoGibbs.jl` this also fails, but if I change `Turing.isgibbscomponent` into just `isgibbscomponent` and import some missing dependencies, the code runs without errors, but I am unable to run `trackdependencies` as in the `README.md` example, I get

```
ERROR: ArgumentError: ⟨Model{var"###evaluator#283",(:x,),Tuple{Float64},(),ModelGen{var"###generator#284",(:x,),(),Tuple{}}}(##evaluator#283, (x = 1.4,), ModelGen{var"###generator#284",(:x,),(),Tuple{}}(##generator#284, NamedTuple()))⟩(, ()...) → 1.4::Float64 does not contain any model call, you should not have reached this point!
```

I am not sure if this has to do with the unusual installation (though there isn't anything else than includes and some standalone definitions happening in `src/AutoGibbs.jl`, I am not sure if Julia module system treats this differently) and so I am making this issue primarily about the `isgibbscomponent` problem. Do you have an idea how to approach this? How do you use the package on your system? Apologies if I am missing something obvious here and thanks a lot!

**Comment by phipsgabler** [comment]
I work with pinned development versions of Turing and DynamicPPL (that's where the missing `isgibbscomponent` comes from).  My intention was that things should work if you instantiate the project from the manifest, but I haven't tried that yet from a clean install.

The other error at first sight seem unrelated, but is proably also due to the fact that the model internals in recent DPPL have changed.
